### ISSUE TITLE
Write Problem Definition - Stakeholders

### ISSUE THREAD

**Issue by dyc3** [dyc3/sys-581-group-project#92]

**Comment by Victor-M-Giraldo** [comment]
@dyc3 Isn't this one already covered by `stakeholders.typ`? Can I go ahead and close this issue?

**Comment by dyc3** [comment]
As long as it fits into the document well.

**Comment by dyc3** [comment]
As long as it fits into the doc well and you've proofread it.

**Comment by Victor-M-Giraldo** [comment]
Did a read through. Think it's fine.
